# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44928bea4022a3030db7f7c9114cd4a9f364e1c5300aa332e49963f948e4d3f003694d2cc082acee5c0d17e0f06e6412c778cbb0bf8755887bc98532ebb27ec2

test:
  secret_key_base: 3f5ae801f4665201561f3e25eccbb73e251dd1f87e18fef1c3f8e31f856f5c00746002123394a1ca94b3b24de499d4996d656725f8a7f6ea826d6b44b33373de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
